version: '3.8'

services:
  app:
    build: .
    container_name: moderation_api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moderation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
